spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=your-very-secure-secret-key-that-is-long-enough
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# QWeather API Configuration
qweather.api.host=mx5ctu8gcb.re.qweatherapi.com
qweather.api.public-key=378AWVDYFU
qweather.api.private-key=MC4CAQAwBQYDK2VwBCIEIHX+7mk+Bo/RN6UUkw4wYYM1OM9ajFF559+Vjj3QOdZX
qweather.api.key-id=T8WJXC4R78
